SET IDENTITY_INSERT dbo.Customers ON
GO
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (1, 'Letha Bolt', 'Croatia', 'Boca Raton', 55, 'Sales Representative');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (2, 'Vanita Kelleher', 'Ghana', 'University Place', 46, 'Revenue Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (3, 'Marcos Abraham', 'Guyana', 'North Royalton', 41, 'Research Engineer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (4, 'Miyoko Mckinney', 'Sri Lanka', 'Atlantic', 32, 'Finance Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (5, 'Adolph Francisco', 'Sri Lanka', 'Marquette', 36, 'Director of Manufacturing');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (6, 'Oma Lawler', 'Swaziland', 'Rochester', 39, 'Research Assistant');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (7, 'Felix Alba', 'Iraq', 'Lindsay', 53, 'Benefit Coordinator');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (8, 'Eusebia Noland', 'Nicaragua', 'Montgomery', 29, 'Training Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (9, 'Denisha Mcginnis', 'Malawi', 'Allen Park', 37, 'Sales Representative');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (10, 'Stanford Sullivan', 'Uruguay', 'Monroe', 57, 'Purchasing Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (11, 'Nathan Salisbury', 'Australia', 'Surfside', 23, 'Board Member');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (12, 'Burton Bunnell', 'Finland', 'Aberdeen', 42, 'Broker');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (13, 'Adah Jameson', 'Luxembourg', 'Rio Rancho', 36, 'Service Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (14, 'Adam Geer', 'Suriname', 'Redwood Falls', 32, 'Facilities Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (15, 'Freeman Selby', 'Slovakia', 'Syracuse', 39, 'Technical Consultant');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (16, 'Laura Barger', 'Zambia', 'Melbourne', 57, 'Vice President');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (17, 'Ariel Hermann', 'France', 'Anaconda', 63, 'Senior Developer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (18, 'Adam Maddox', 'Austria', 'Castle Shannon', 47, 'Security Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (19, 'Winnifred Brantley', 'Canada', 'Saraland', 35, 'Business Consultant');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (20, 'Gayle Baugh', 'Ukraine', 'Eagar', 54, 'Sales Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (21, 'Delcie Abney', 'Guatemala', 'Portola Valley', 24, 'Development Engineer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (22, 'Kasey Furr', 'Guyana', 'Clayton', 21, 'Research Engineer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (23, 'Gertie Abel', 'Swaziland', 'Murphysboro', 38, 'Project Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (24, 'Myles Angel', 'Denmark', 'Elko', 24, 'Vice President');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (25, 'Jerome Gipson', 'Bangladesh', 'Augusta', 20, 'Chief Information Officer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (26, 'Lilla Perez', 'Denmark', 'Negaunee', 63, 'Commercial Director');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (27, 'Josephine Norwood', 'Mongolia', 'Aberdeen', 47, 'Application Engineer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (28, 'Elli Robertson', 'Italy', 'Blakely', 28, 'Contract Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (29, 'Curtis Hutson', 'Albania', 'Dahlonega', 29, 'Assistant');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (30, 'Melia Gates', 'Sierra Leone', 'Albany', 51, 'Secretary');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (31, 'Marc Pickering', 'Saudi Arabia', 'Pigeon Forge', 41, 'Vice President');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (32, 'Alida Jobe', 'Bangladesh', 'Talladega', 21, 'Revenue Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (33, 'Cordelia Key', 'Moldova', 'Redding', 21, 'Secretary');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (34, 'Reba Gregg', 'Botswana', 'Maple Heights', 18, 'Logistics Consultant');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (35, 'Jarod Bourgeois', 'Nigeria', 'Chanhassen', 25, 'Research Engineer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (36, 'Oliva Coble', 'New Zealand', 'Columbia Falls', 65, 'Technology Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (37, 'Corey Musgrove', 'Tunisia', 'Columbia', 53, 'Credit Analyst');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (38, 'Bud Grubbs', 'Bahrain', 'Strongsville', 38, 'Chief Financial Officer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (39, 'Newton Graves', 'Brazil', 'Beaver', 31, 'Specialist');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (40, 'Tamica Goins', 'Italy', 'South Holland', 50, 'Network Administrator');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (41, 'Bertram Herzog', 'Panama', 'Aberdeen', 57, 'Programmer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (42, 'Malcolm Coward', 'Uruguay', 'Doraville', 43, 'Secretary');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (43, 'Carley Valdez', 'Israel', 'Malden', 39, 'Chief Executive Officer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (44, 'Lizzie Krueger', 'Afghanistan', 'Santa Fe', 24, 'Admin');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (45, 'Celestine Hong', 'Argentina', 'Fairlawn', 38, 'Section Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (46, 'Shonda Leake', 'Netherlands', 'Pismo Beach', 48, 'Contract Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (47, 'Hubert Waldrop', 'Cuba', 'Abbeville', 21, 'Building Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (48, 'Alphonso Meeks', 'Fiji', 'Michigan City', 41, 'Admin');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (49, 'Aimee Stamm', 'Malawi', 'Wapato', 48, 'Secretary');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (50, 'Sonia Ackerman', 'Malaysia', 'Ogdensburg', 43, 'Technical Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (51, 'Derrick Ruiz', 'Sweden', 'Spokane', 39, 'Development Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (52, 'Alejandro Espinal', 'Australia', 'Fox Chapel', 39, 'Technical Editor');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (53, 'Myrtis Thornhill', 'Namibia', 'Asbury Park', 27, 'Technical Editor');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (54, 'Calvin Looney', 'Panama', 'Sioux Center', 23, 'Senior Architect');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (55, 'Deedee Strange', 'Botswana', 'Mountlake Terrace', 21, 'Vice President');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (56, 'Burt Hughes', 'Colombia', 'Waterloo', 55, 'Director of Human Resources');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (57, 'Calvin Abrams', 'Canada', 'Hawthorn Woods', 22, 'Assistant');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (58, 'Hobert Adam', 'Croatia', 'Chittenango', 40, 'Sales Representative');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (59, 'Adan Pulido', 'Saudi Arabia', 'Anchorage', 20, 'Senior Specialist');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (60, 'Abel Christian', 'Argentina', 'Arlington Heights', 55, 'Regional Vice President');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (61, 'Jeanna Maxwell', 'Panama', 'Huron', 62, 'Programmer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (62, 'Alice Gonzales', 'Nepal', 'Winchester', 37, 'Product Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (63, 'Ronnie Roby', 'Croatia', 'East Chicago', 38, 'Security Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (64, 'Mervin Lyon', 'Malaysia', 'Orlando', 46, 'Chief Financial Officer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (65, 'Abram Fenton', 'Nigeria', 'Abilene', 38, 'Commercial Director');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (66, 'Carlton Beaudoin', 'Sweden', 'Ukiah', 20, 'Buying Agent');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (67, 'Alexa Saucedo', 'Australia', 'Oakland Park', 19, 'Board Member');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (68, 'Bryce Estrada', 'Belize', 'Bartlett', 36, 'Commercial Director');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (69, 'Milton Gay', 'Nicaragua', 'Albany', 20, 'Training Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (70, 'Halley Bostic', 'Botswana', 'Live Oak', 38, 'Vice President');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (71, 'Darrick Olmstead', 'Yemen', 'Albany', 37, 'Specialist');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (72, 'Logan Flannery', 'Kuwait', 'Douglass Hills', 42, 'Secretary');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (73, 'Armando Alvarez', 'Italy', 'Holly Springs', 42, 'Network Administrator');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (74, 'Glynis Redman', 'Brazil', 'Burlington', 41, 'Secretary');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (75, 'Sonya Tinsley', 'Chile', 'Snohomish', 19, 'Project Leader');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (76, 'Machelle Andersen', 'Panama', 'Leonia', 40, 'Admin');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (77, 'Owen Alston', 'Philippines', 'Scarsdale', 46, 'Service Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (78, 'Bradford Alfaro', 'Belgium', 'Alpine', 48, 'Senior Accountant');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (79, 'Benito Agee', 'Portugal', 'Soledad', 50, 'Software Engineer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (80, 'Alan Judd', 'Iceland', 'La Grange', 29, 'Vice President');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (81, 'Abram Swank', 'Nicaragua', 'Bismarck', 18, 'Specialist');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (82, 'Elaina Gruber', 'Norway', 'Hutto', 18, 'Engineer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (83, 'Debbra Packer', 'Uganda', 'St. Augustine Beach', 21, 'Producer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (84, 'Freeman Blevins', 'Luxembourg', 'Royal Palm Beach', 18, 'Technical Editor');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (85, 'Drew Burt', 'Spain', 'Calabasas', 58, 'Support Engineer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (86, 'Rivka Caron', 'Ecuador', 'Abbeville', 43, 'Senior Specialist');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (87, 'Lesia Hatch', 'South Africa', 'Hampton', 54, 'Computer Operator');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (88, 'Janis Gonsalves', 'United Kingdom', 'Warren', 59, 'Chief Executive Officer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (89, 'Selina Pfeiffer', 'Argentina', 'Coshocton', 53, 'Assistant Vice President');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (90, 'Johnathan Magana', 'Latvia', 'East Peoria', 43, 'Account Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (91, 'Hosea Spears', 'Pakistan', 'Elmsford', 37, 'Business Analyst');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (92, 'Graham Alger', 'Italy', 'Choctaw', 43, 'Building Manager');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (93, 'Kizzy Hightower', 'Slovenia', 'Hemet', 46, 'Director of Marketing');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (94, 'Sanjuanita Conners', 'Luxembourg', 'Kittanning', 19, 'Finance Controller');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (95, 'Tanner Van', 'Czech Rep.', 'Poulsbo', 44, 'Chief Technology Officer');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (96, 'Abel Paulson', 'Botswana', 'Baldwin', 47, 'Application Architect');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (97, 'Abdul Freed', 'Latvia', 'Telford', 31, 'Advertising Director');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (98, 'Ora Dorris', 'Kenya', 'Abilene', 65, 'Vice President');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (99, 'Abbie Gurley', 'Belize', 'Alexandria', 36, 'Director of Customer Support');
INSERT dbo.Customers(ID, FullName, Country, City, Age, Job) VALUES (100, 'Bradford Broderick', 'Czech Rep.', 'Cumberland', 30, 'Senior Specialist');
GO
SET IDENTITY_INSERT dbo.Customers OFF
GO